admins: [1919745140] 

forwards:
  - source: -1001713025945
    dest: [-1001661609544,-1001569683935,-1001612020625]

plugins:
  filter:
    text:
      "RUN BANAKAR OUT": Run Banakar Out
      "CATCH OUT✔️✔️": 🚾 CATCH OUT 🚾
      "WIDE ✔️✔️" : 🎾 WIDE 🎾
      "RUN OUT✔️✔️": 🚾 RUN OUT 🚾
      "✔️✔️": " "
